# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Laurent Délèris
#email: 
description: > # this means to ignore newlines until "baseurl:"
  Un peu de veille technologique sur l'instrumentation embarquée
  open source.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://deleris.com" # the base hostname & protocol for your site
twitter_username: ldeleris
github_username:  ldeleris
viadeo_username:  ldeleris
bitbucket_username:  ldeleris
linkedin_username: ldeleris

# Build settings
markdown: kramdown
